<?php
namespace Admin\Controller;
use Think\Controller;
/**
 * 
 */
class AdminController extends BaseController {
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}

	/**
	 * [index 首页]
	 * @return [type] [description]
	 */
    public function index(){
		$group = 0;
		if($_SESSION['Admin']['login']['gid']){
			$group = explode(',',$_SESSION['Admin']['login']['gid']);
			if(in_array(5,$group) || $_SESSION['Admin']['login']['gid']==-1){
				$group = 1;
			}
		}
		$this->group= $group;
		$map='';
		if($_SESSION['Admin']['login']['gid']!=-1){
			$map['id']=$_SESSION['Admin']['login']['id'];
		}

		$this->list=$list=$this->getlist(M('admin'),$map);
    	$this->display();

    }

	public function check($id=0){
		if(!$id){
			$this->error('参数错误');
		}
		$this->admin=$admin = M('admin')->find($id);
		$this->display();
	}
	public function add(){
		$this->model=$model = M('model')->field('id,name,contr_name')->where('fid=0 and `show`=0 and status=0')->select();
		$this->display();
	}
	public function addhd(){

		if(I('post.gid')==''){
			$this->ajaxReturn(array('status'=>0,'msg'=>'请填写至少一个权限'));
		}else{
			$gid = implode(',',$_POST['gid']);
		}
		$admin = M('admin')->where('username="'.I('post.username').'"')->find();
		if(!empty($admin)){
			$this->ajaxReturn(array('status'=>0,'msg'=>'管理员账号已存在,请换一个'));
		}
		$data = array(
			'username'=>I('post.username'),
			'password'=>md5(trim(I('post.password'))),
			'hash'=>base64_encode(I('post.password')),
			'gid'=>$gid
		);

		if(!M('admin')->add($data)){
			$this->ajaxReturn(array('status'=>0,'msg'=>'管理员账号添加失败,请稍后重试'));
		}
		$this->ajaxReturn(array('status'=>1,'msg'=>'管理员账号成功','redirect'=>U('index')));
	}
	public function check_group($id=0){
		if(!$id){
			$this->error('参数错误');
		}
		$this->model=$model = M('model')->field('id,name,contr_name')->where('fid=0 and `show`=0 and status=0')->select();

		$this->admin=$admin = M('admin')->find($id);
		$this->tgid = explode(',',$admin['gid']);
		$this->display();
	}

	public function check_groups(){
		$gid = implode(',',$_POST['gid']);
		$data = array(
			'id'=>I('post.id'),
			'gid'=>$gid,
			'date'=>time()
		);

		if(!M('admin')->save($data)){
			$this->ajaxReturn(array('status'=>0,'msg'=>'操作失败，请稍后重试'));
		}
		$this->ajaxReturn(array('status'=>1,'msg'=>'操作成功','redirect'=>U('index')));
	}
	public function del($id=0){
		if(!$id){
			$this->ajaxReturn(array('status'=>0,'msg'=>'参数错误'));
		}
		if(!M('admin')->delete($id)){
			$this->ajaxReturn(array('status'=>0,'msg'=>'管理员账号删除失败'));
		}
		$this->ajaxReturn(array('status'=>1,'msg'=>'管理员账号删除成功','redirect'=>U('index')));
	}
	public function check_password(){

		if(IS_POST){
			$id = I('post.id');
			if(empty($id)){
				$this->ajaxReturn(array('status'=>0,'msg'=>'还未登录,请登录修改'));
			}
			$member = M('admin')->find($id);


			if(empty($member)){
				$this->ajaxReturn(array('status'=>0,'msg'=>'没有此用户'));
			}
			if($member['password'] != md5(I('post.old_pwd'))){
				$this->ajaxReturn(array('status'=>0,'msg'=>'原密码错误'));
			}

			$data=array(
				'id'=>$id,
				'password'=>md5(I('post.password')),
				'hash'=>base64_encode(I('post.password'))
			);

			if(!M('admin')->save($data)){
				$this->ajaxReturn(array('status'=>0,'msg'=>'密码修改失败,请重试!'));
			}
			$this->ajaxReturn(array('status'=>1,'msg'=>'密码修改成功','redirect'=>U('index')));
		}
	}
}