<?php
/**
 * Created by PhpStorm.
 * User: dong
 * Date: 2016/5/23
 * Time: 10:42
 */

namespace Home\Controller;
use Think\Controller;

class QueryController extends BaseController{
    private $homepage='';
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function express($no='',$decode=1){
        if(!$decode){
            $no = getDeEncyptStr($no);
        }
        $order = M('order')->field('id,username,phone,shun_feng,ordid,ordtime,sums,wine,post_address,post_userinfo,post_goods_express,post_goods_time,post_wine_express,post_wine_time')->where(array('ordid'=>$no))->find();
        if(!empty($order)){
            if($order['isused']==2){
                $goods= M('article')->find($order['productid']);
                $goods['count']=1;
                $order['pro'][]=$goods;
            }else{
                foreach (explode('|',$order['sums']) as $k=>$v){
                    $temp = explode('_',$v);
                    if(strstr($v,'wine')){
                        $wine= M('article')->find($temp[1]);
                        $wine['count']=$temp[2];
                        $wine['price']=$temp[3];
                        $wine['totals']=$temp[3]*$temp[2];
                        $order['pro'][]=$wine;
                    }else if (strstr($v,'goods')){
                        $goods= M('article')->find($temp[1]);
                        $goods['count']=$temp[2];
                        $goods['price']=$temp[3];
                        $goods['totals']=$temp[3]*$temp[2];
                        $order['pro'][]=$goods;
                    }else{
                        $coupon= M('coupons')->where(array('coupon_cid'=>$temp[1]))->find();
                        $pr = M('article')->field('keywords,column_id,image,content,tprice,extend')->find($temp[1]);
                        $coupon['title']=$coupon['coupons_title'];
                        $coupon['count']=$temp[2];
                        $coupon['price']=$temp[3];
                        $coupon['totals']=$temp[3]*$temp[2];
                        $coupon=array_merge($coupon,$pr);
                        $order['pro'][]=$coupon;
                    }
                }
            }
        }
        //p($order);die;
        $this->vo=$order;
       // $data = $this->fetch();

        $isMobile = session('isMobile');
        if(!$isMobile){
            $this->display();
        }else{
            $this->display('Wap/View/Query/index');
        }


        //$this->ajaxReturn(array('status'=>1,'body'=>$data));
    }

    public function get_url($no=''){
        if(empty($no)){
            $this->ajaxReturn(array('status'=>0,'msg'=>'输入订单号'));
        }
        $order = M('order')->field('id,username,phone,ordid,sums,wine,post_address,post_userinfo,post_goods_express,post_goods_time,post_wine_express,post_wine_time')->where(array('ordid'=>$no))->find();
        if(empty($order)){
            $this->ajaxReturn(array('status'=>0,'msg'=>'输入的订单号不正确'));
        }
        $this->ajaxReturn(array('status'=>1,'redirect'=>U('express?no='.$no)));
    }

    //注意 city方法 本身是 protected 方法
    protected function _empty(){
        header("HTTP/1.0 404 Not Found");//使HTTP返回404状态码

       if(strstr($_SERVER['REQUEST_URI'],'/t')){
          $url = str_replace('/t','http://ni2.org',$_SERVER['REQUEST_URI']);
           header('location:'.$url);
       }
        $this->assign('home',$this->homepage);
        $this->display("Common:404");
    }

}