<?php
/**
 * Created by PhpStorm.
 * User: dong
 * Date: 2016/5/23
 * Time: 10:42
 */

namespace Wap\Controller;
use Think\Controller;

class RedwineController extends BaseController{
    private $Wappage='';
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $map['status']=0;
        $map['column_id']=array('eq',5);

        $form = I('get.from');
        $to = I('get.to');
        if($form || $to){

            $map['tprice']  = array('between',array($form,$to));
            if(!$form){
                $form=10;
            }
            $hg = substr($form,0,1);
            $this->hg= ($hg!='-')?$hg:1;
        }
        $list = $this->getlist(M('article'),$map,'','',8);
        $this->list=$list;
        $this->display();
    }

    public function details($id=0){
        if(!$id){
            $this->display("Common:404");
        }
        $coupons = M('article')->find($id);
        //$t = explode('|',$coupons['coupons_val']);
        //$coupons['coupons_product'] =  M('article')->find($t[0]);
        $this->vo=$coupons;
        $this->get_order=$this->get_new_order();
        $this->display();
    }
    //注意 city方法 本身是 protected 方法
    protected function _empty(){
        header("HTTP/1.0 404 Not Found");//使HTTP返回404状态码

       if(strstr($_SERVER['REQUEST_URI'],'/t')){
          $url = str_replace('/t','http://ni2.org',$_SERVER['REQUEST_URI']);
           header('location:'.$url);
       }
        $this->assign('Wap',$this->Wappage);
        $this->display("Common:404");
    }

}